# Generated by Django 5.2.16 on 2026-07-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcms_blog', '0006_auto_20190303_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttitle',
            name='published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
